// src/components/LibraryView.tsx
import { createSignal, createEffect, onCleanup, Show, For, createMemo } from "solid-js";
import { Archive, FolderOpen, Loader2, X, RefreshCw, BookOpen } from "lucide-solid";
import { save } from "@tauri-apps/plugin-dialog";
import { api, type LibraryInfo } from "@/lib/tauri";
import { uiStore } from "@/stores/ui";
import { settings } from "@/stores/settings";
import { formatBytes } from "@/lib/utils";

export default function LibraryView() {
  const [loading, setLoading] = createSignal(true);
  const [error, setError] = createSignal<string | null>(null);
  const [exportingPath, setExportingPath] = createSignal<string | null>(null);
  const [exportError, setExportError] = createSignal<string | null>(null);
  const [loadTick, setLoadTick] = createSignal(0);

  const libraries = createMemo(() => uiStore.knownLibraries);
  const totalDocs = createMemo(() =>
    libraries().reduce((s, l) => s + l.n_docs, 0),
  );
  const totalBytes = createMemo(() =>
    libraries().reduce((s, l) => s + l.size_bytes, 0),
  );

  createEffect(() => {
    const _tick = loadTick();
    const root = settings.libraryRoot;
    if (!root) {
      setLoading(false);
      return;
    }
    let cancelled = false;
    setLoading(true);
    setError(null);

    api.listLibraries(root)
      .then((libs) => {
        if (!cancelled) {
          uiStore.setKnownLibraries(libs);
          setLoading(false);
        }
      })
      .catch((e) => {
        if (!cancelled) {
          setError(String(e));
          setLoading(false);
        }
      });
    onCleanup(() => { cancelled = true; });
  });

  async function handleExport(lib: LibraryInfo, e: MouseEvent) {
    e.stopPropagation();
    setExportError(null);
    const dest = await save({
      defaultPath: `${lib.name}.zip`,
      filters: [{ name: "ZIP archive", extensions: ["zip"] }],
    });
    if (!dest) return;
    setExportingPath(lib.path);
    try {
      const result = await api.exportLibraryZip(lib.path, dest);
      await api.revealInFinder(result.dest);
    } catch (e) {
      setExportError(String(e));
    } finally {
      setExportingPath(null);
    }
  }

  return (
    <div class="df-canvas">
      <div class="df-canvas-head">
        <h1 class="df-canvas-title">Library</h1>
        <div class="df-headstats">
          <div class="df-headstat">
            <span class="df-headstat-num">{libraries().length}</span>
            <span class="df-headstat-label">libraries</span>
          </div>
          <div class="df-headstat">
            <span class="df-headstat-num">{totalDocs()}</span>
            <span class="df-headstat-label">docs saved</span>
          </div>
          <div class="df-headstat">
            <span class="df-headstat-num">{formatBytes(totalBytes())}</span>
            <span class="df-headstat-label">on disk</span>
          </div>
        </div>
      </div>

      <div class="df-canvas-body" style={{ "padding-top": "var(--pad-6)" }}>
        <Show when={exportError()}>
          <div class="df-banner bad" style={{ "margin-bottom": "var(--pad-4)" }}>
            <X size={14} />
            <div class="df-banner-body">
              <strong>Export failed.</strong> {exportError()}
            </div>
            <button
              class="df-banner-x"
              onClick={() => setExportError(null)}
              aria-label="Dismiss"
            >
              <X size={12} />
            </button>
          </div>
        </Show>

        <Show when={loading()}>
          <div style={{
            display: "flex",
            "justify-content": "center",
            padding: "var(--pad-9) 0",
          }}>
            <Loader2 size={24} class="spin" style={{ color: "var(--ink-3)" }} />
          </div>
        </Show>

        <Show when={!loading() && error()}>
          <div class="df-banner bad">
            <X size={14} />
            <div class="df-banner-body">
              <strong>Could not list libraries.</strong> {error()}
            </div>
            <button
              class="df-btn sm"
              onClick={() => setLoadTick((n) => n + 1)}
              style={{ "flex-shrink": 0 }}
            >
              <RefreshCw size={12} /> Retry
            </button>
          </div>
        </Show>

        <Show when={!loading() && !error() && libraries().length === 0}>
          <div class="df-empty">
            <div class="df-empty-mark">
              <BookOpen size={28} />
            </div>
            <h3 class="df-empty-title">No libraries yet</h3>
            <p class="df-empty-sub">
              Run a search from Discover and saved documents will land here as a
              library collection.
            </p>
            <button class="df-btn accent" onClick={() => uiStore.setView("find")}>
              Go to Discover
            </button>
          </div>
        </Show>

        <Show when={!loading() && libraries().length > 0}>
          <div class="df-libgrid">
            <For each={libraries()}>{(lib) => {
              const isActive = () => uiStore.activeLibrary?.path === lib.path;
              const isExporting = () => exportingPath() === lib.path;
              return (
                <button
                  class="df-libcard"
                  classList={{ active: isActive() }}
                  onClick={() => uiStore.setActiveLibrary(lib)}
                >
                  <div class="df-libcard-head">
                    <span class="df-libcard-q" title={lib.query ?? lib.name}>
                      {lib.query ?? lib.name}
                    </span>
                  </div>
                  <div class="df-libcard-meta">
                    <span><strong>{lib.n_docs}</strong> docs</span>
                    <span><strong>{formatBytes(lib.size_bytes)}</strong></span>
                  </div>
                  <div class="df-libcard-actions" onClick={(e) => e.stopPropagation()}>
                    <button
                      class="df-btn sm"
                      onClick={(e) => handleExport(lib, e)}
                      disabled={isExporting()}
                    >
                      <Show when={isExporting()} fallback={<Archive size={12} />}>
                        <Loader2 size={12} class="spin" />
                      </Show>
                      Export ZIP
                    </button>
                    <button
                      class="df-btn sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        api.revealInFinder(lib.path);
                      }}
                    >
                      <FolderOpen size={12} /> Show
                    </button>
                  </div>
                </button>
              );
            }}</For>
          </div>
        </Show>
      </div>
    </div>
  );
}

// src/components/LibraryView.svelte
<script lang="ts">
  import { save } from "@tauri-apps/plugin-dialog";
  import {
    ArrowRight,
    CheckCheck,
    FileArchive,
    FolderOpen,
    Library as LibraryIcon,
    Loader2,
  } from "lucide-svelte";
  import { api, type LibraryInfo } from "@/lib/tauri";
  import { formatBytes } from "@/lib/utils";
  import { settingsStore } from "@/stores/settings.svelte";
  import { uiStore } from "@/stores/ui.svelte";

  let libraries = $state<LibraryInfo[]>([]);
  let loading = $state(false);
  let exportingPath = $state<string | null>(null);
  let justExported = $state<string | null>(null);
  let error = $state<string | null>(null);

  $effect(() => {
    if (!settingsStore.libraryRoot) {
      api.defaultLibraryDir().then((d) => settingsStore.set({ libraryRoot: d.library_root }));
      return;
    }
    loadLibraries();
  });

  async function loadLibraries() {
    loading = true;
    try {
      libraries = await api.listLibraries(settingsStore.libraryRoot);
    } catch {
      libraries = [];
    } finally {
      loading = false;
    }
  }

  async function exportZip(l: LibraryInfo) {
    error = null;
    const dest = await save({
      defaultPath: `${l.name}.zip`,
      filters: [{ name: "ZIP archive", extensions: ["zip"] }],
    });
    if (!dest) return;
    exportingPath = l.path;
    try {
      const result = await api.exportLibraryZip(l.path, dest);
      justExported = result.dest;
      setTimeout(() => (justExported = null), 4000);
      await api.revealInFinder(result.dest);
    } catch (e) {
      error = String(e);
    } finally {
      exportingPath = null;
    }
  }
</script>

<div class="space-y-5">
  <header>
    <h1 class="text-2xl font-semibold">Library</h1>
  </header>

  {#if error}
    <div class="rounded-md border border-rose-500/40 bg-rose-50 px-3 py-2 text-sm text-rose-700">
      {error}
    </div>
  {/if}

  {#if justExported}
    <div class="flex items-center gap-2 rounded-md border border-emerald-500/40 bg-emerald-50 px-3 py-2 text-sm text-emerald-700">
      <CheckCheck class="h-4 w-4" />
      Exported to {justExported}
    </div>
  {/if}

  {#if loading}
    <div class="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-8 text-center text-sm text-[var(--color-muted-foreground)]">
      Loading…
    </div>
  {:else if libraries.length === 0}
    <div class="rounded-xl border border-dashed border-[var(--color-border)] bg-[var(--color-card)] p-10 text-center">
      <LibraryIcon class="mx-auto mb-3 h-8 w-8 text-[var(--color-muted-foreground)]" />
      <h2 class="text-base font-medium">No libraries yet</h2>
      <p class="mx-auto mt-1 max-w-md text-sm text-[var(--color-muted-foreground)]">
        Run a search in Discover and we'll save the downloaded documents here.
      </p>
      <button
        class="mt-4 px-6 py-2 rounded-lg bg-[var(--color-primary)] text-white font-medium hover:opacity-90 inline-flex items-center gap-2"
        onclick={() => uiStore.setView("find")}
      >
        Go to Discover
        <ArrowRight class="h-4 w-4" />
      </button>
    </div>
  {:else}
    <div class="grid grid-cols-1 gap-2 md:grid-cols-2">
      {#each libraries as l (l.path)}
        {@const isActive = uiStore.activeLibrary?.path === l.path}
        {@const isExporting = exportingPath === l.path}
        <div
          class="flex flex-col gap-3 rounded-xl border p-4 text-left transition-colors {isActive ? 'border-[var(--color-primary)]/60 bg-[var(--color-primary)]/5' : 'border-[var(--color-border)] bg-[var(--color-card)]'}"
        >
          <button
            type="button"
            onclick={() => uiStore.setActiveLibrary(l)}
            class="text-left group"
          >
            <div class="truncate text-sm font-medium group-hover:text-[var(--color-primary)]" title={l.query}>
              {l.query}
            </div>
            <div class="mt-1 flex items-center gap-2 text-xs text-[var(--color-muted-foreground)]">
              <span>{l.n_docs} document{l.n_docs === 1 ? "" : "s"}</span>
              {#if l.size_bytes > 0}
                <span>·</span>
                <span>{formatBytes(l.size_bytes)}</span>
              {/if}
            </div>
          </button>

          <div class="flex flex-wrap items-center gap-2">
            <button
              class="px-3 py-1.5 rounded-lg bg-[var(--color-primary)] text-white text-xs font-medium hover:opacity-90 disabled:opacity-50 inline-flex items-center gap-2"
              onclick={() => exportZip(l)}
              disabled={isExporting}
            >
              {#if isExporting}
                <Loader2 class="h-3.5 w-3.5 animate-spin" />
                Zipping…
              {:else}
                <FileArchive class="h-3.5 w-3.5" />
                Export ZIP
              {/if}
            </button>
            <button
              class="px-3 py-1.5 rounded-lg border border-[var(--color-border)] text-xs font-medium hover:bg-[var(--color-accent)] inline-flex items-center gap-2"
              onclick={() => api.revealInFinder(l.path)}
            >
              <FolderOpen class="h-3.5 w-3.5" />
              Show
            </button>
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>
