// src/components/SettingsView.svelte
<script lang="ts">
  import {
    FileText,
    FolderOpen,
    Server,
    Loader2,
    CheckCircle2,
  } from "lucide-svelte";
  import { api, type LogInfo } from "@/lib/tauri";
  import { formatBytes } from "@/lib/utils";
  import { settingsStore } from "@/stores/settings.svelte";

  let logInfo = $state<LogInfo | null>(null);
  let settingUpSearx = $state(false);
  let searxResult = $state<string | null>(null);
  let searxError = $state<string | null>(null);

  $effect(() => {
    api.runLogInfo().then((info) => (logInfo = info)).catch(() => (logInfo = null));
  });

  async function handleSetupSearx() {
    settingUpSearx = true;
    searxResult = null;
    searxError = null;
    try {
      searxResult = await api.setupSearXNG();
    } catch (e) {
      searxError = String(e);
    } finally {
      settingUpSearx = false;
    }
  }

  async function refreshLog() {
    try {
      logInfo = await api.runLogInfo();
    } catch {
      logInfo = null;
    }
  }
</script>

<div class="space-y-5">
  <header>
    <h1 class="text-2xl font-semibold">Settings</h1>
  </header>

  <section class="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5">
    <h2 class="mb-3 text-sm font-medium">Discovery</h2>
    <div class="grid grid-cols-1 gap-3 md:grid-cols-3">
      <div>
        <label class="block text-xs font-medium text-[var(--color-muted-foreground)] mb-1">Per source</label>
        <input
          type="number"
          min="1"
          bind:value={settingsStore.perSource}
          onchange={() => settingsStore.save()}
          class="w-full rounded-md border border-[var(--color-border)] bg-transparent p-2 text-sm"
        />
        <p class="mt-1 text-[11px] text-[var(--color-muted-foreground)]">
          Max documents per source per sub-query.
        </p>
      </div>
      <div>
        <label class="block text-xs font-medium text-[var(--color-muted-foreground)] mb-1">Max total</label>
        <input
          type="number"
          min="1"
          bind:value={settingsStore.maxTotal}
          onchange={() => settingsStore.save()}
          class="w-full rounded-md border border-[var(--color-border)] bg-transparent p-2 text-sm"
        />
        <p class="mt-1 text-[11px] text-[var(--color-muted-foreground)]">
          Hard cap across all sources.
        </p>
      </div>
      <div>
        <label class="block text-xs font-medium text-[var(--color-muted-foreground)] mb-1">Parallel downloads</label>
        <input
          type="number"
          min="1"
          max="32"
          bind:value={settingsStore.concurrency}
          onchange={() => settingsStore.save()}
          class="w-full rounded-md border border-[var(--color-border)] bg-transparent p-2 text-sm"
        />
        <p class="mt-1 text-[11px] text-[var(--color-muted-foreground)]">
          Higher = faster but more risk of rate limits.
        </p>
      </div>
    </div>
  </section>

  <section class="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5">
    <h2 class="mb-3 text-sm font-medium">Library folder</h2>
    <input
      bind:value={settingsStore.libraryRoot}
      onchange={() => settingsStore.save()}
      class="w-full rounded-md border border-[var(--color-border)] bg-transparent p-2 text-xs font-mono"
    />
  </section>

  <section class="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5">
    <h2 class="mb-1 text-sm font-medium">Search Infrastructure</h2>
    <p class="mb-3 text-[11px] text-[var(--color-muted-foreground)]">
      SearXNG provides privacy-respecting search across dozens of engines.
      If you have Docker installed, we can set up a local instance for you.
    </p>
    <div class="space-y-3">
      <button
        onclick={handleSetupSearx}
        disabled={settingUpSearx}
        class="px-4 py-2 rounded-lg border border-[var(--color-border)] text-sm font-medium hover:bg-[var(--color-accent)] inline-flex items-center gap-2"
      >
        {#if settingUpSearx}
          <Loader2 class="h-3.5 w-3.5 animate-spin" />
          Setting up...
        {:else}
          <Server class="h-3.5 w-3.5" />
          Setup SearXNG with Docker
        {/if}
      </button>

      {#if searxResult}
        <div class="flex items-start gap-2 rounded-md border border-emerald-500/30 bg-emerald-50 p-3 text-[11px] text-emerald-800">
          <CheckCircle2 class="mt-0.5 h-3.5 w-3.5 shrink-0" />
          <div class="space-y-1">
            <p class="font-medium">Success!</p>
            <pre class="max-h-32 overflow-auto whitespace-pre-wrap font-mono text-[10px] opacity-80">
              {searxResult}
            </pre>
          </div>
        </div>
      {/if}

      {#if searxError}
        <div class="flex items-start gap-2 rounded-md border border-rose-500/30 bg-rose-50 p-3 text-[11px] text-rose-800">
          <CheckCircle2 class="mt-0.5 h-3.5 w-3.5 shrink-0 rotate-45" />
          <div class="space-y-1">
            <p class="font-medium">Setup Failed</p>
            <p class="opacity-80">{searxError}</p>
          </div>
        </div>
      {/if}
    </div>
  </section>

  <section class="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5">
    <h2 class="mb-1 text-sm font-medium">Run log</h2>
    <p class="mb-3 text-[11px] text-[var(--color-muted-foreground)]">
      Every query, source error, and download outcome is appended here.
      Share this file when reporting issues — it's the easiest way to
      diagnose failed downloads.
    </p>
    {#if logInfo}
      <div class="space-y-2">
        <code class="block truncate rounded-md border border-[var(--color-border)] bg-[var(--color-muted)] px-2.5 py-1.5 font-mono text-[11px]">
          {logInfo.path}
        </code>
        <div class="flex items-center gap-2 text-[11px] text-[var(--color-muted-foreground)]">
          <span>
            {logInfo.exists
              ? formatBytes(logInfo.size_bytes)
              : "not yet written"}
          </span>
        </div>
        <div class="flex items-center gap-2">
          <button
            onclick={() => api.revealInFinder(logInfo!.path)}
            disabled={!logInfo.exists}
            class="px-3 py-1.5 rounded-lg border border-[var(--color-border)] text-xs font-medium hover:bg-[var(--color-accent)] inline-flex items-center gap-2 disabled:opacity-50"
          >
            <FolderOpen class="h-3.5 w-3.5" />
            Show log in Finder
          </button>
          <button
            onclick={refreshLog}
            class="px-3 py-1.5 rounded-lg border border-[var(--color-border)] text-xs font-medium hover:bg-[var(--color-accent)] inline-flex items-center gap-2"
          >
            <FileText class="h-3.5 w-3.5" />
            Refresh
          </button>
        </div>
      </div>
    {:else}
      <div class="text-xs text-[var(--color-muted-foreground)]">
        Resolving log path…
      </div>
    {/if}
  </section>
</div>

// src/components/SettingsView.tsx
import { createSignal, onMount, Show } from "solid-js";
import { Server, FolderOpen, FileText, Loader2, CheckCircle2 } from "lucide-solid";
import { api, type LogInfo } from "@/lib/tauri";
import { settings, setSettings, saveSettings } from "@/stores/settings";
import { formatBytes } from "@/lib/utils";

export default function SettingsView() {
  const [logInfo, setLogInfo] = createSignal<LogInfo | null>(null);
  const [settingUpSearx, setSettingUpSearx] = createSignal(false);
  const [searxResult, setSearxResult] = createSignal<string | null>(null);
  const [searxError, setSearxError] = createSignal<string | null>(null);

  onMount(async () => {
    setLogInfo(await api.runLogInfo().catch(() => null));
  });

  async function handleSetupSearx() {
    setSettingUpSearx(true);
    setSearxResult(null);
    setSearxError(null);
    try {
      const output = await api.setupSearXNG();
      setSearxResult(output);
      const match = output.match(/^SEARXNG_URL=(.+)$/m);
      if (match) {
        setSettings("searxngUrl", match[1].trim());
        saveSettings();
      }
    } catch (e) {
      setSearxError(String(e));
    } finally {
      setSettingUpSearx(false);
    }
  }

  function numInput(field: "perSource" | "maxTotal" | "concurrency") {
    return (e: InputEvent & { currentTarget: HTMLInputElement }) => {
      const v = parseInt(e.currentTarget.value, 10);
      if (!isNaN(v) && v > 0) {
        setSettings(field, v);
        saveSettings();
      }
    };
  }

  return (
    <div class="h-full overflow-y-auto">
      <div class="mx-auto max-w-2xl space-y-6 p-6 pt-10">
        <h1 class="text-xl font-semibold">Settings</h1>

        {/* Discovery settings */}
        <section class="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5">
          <h2 class="mb-4 text-sm font-semibold">Discovery</h2>
          <div class="grid grid-cols-3 gap-4">
            <label class="block">
              <span class="mb-1 block text-xs font-medium text-[var(--color-muted-foreground)]">Per source</span>
              <input
                type="number"
                min="1"
                value={settings.perSource}
                onInput={numInput("perSource")}
                class="w-full rounded-lg border border-[var(--color-border)] bg-transparent px-3 py-2 text-sm outline-none focus:border-[var(--color-primary)] focus:ring-2 focus:ring-[var(--color-primary)]/20 transition-colors"
              />
              <p class="mt-1 text-[10px] text-[var(--color-muted-foreground)]">Max docs per source per sub-query</p>
            </label>
            <label class="block">
              <span class="mb-1 block text-xs font-medium text-[var(--color-muted-foreground)]">Max total</span>
              <input
                type="number"
                min="1"
                value={settings.maxTotal}
                onInput={numInput("maxTotal")}
                class="w-full rounded-lg border border-[var(--color-border)] bg-transparent px-3 py-2 text-sm outline-none focus:border-[var(--color-primary)] focus:ring-2 focus:ring-[var(--color-primary)]/20 transition-colors"
              />
              <p class="mt-1 text-[10px] text-[var(--color-muted-foreground)]">Hard cap across all sources</p>
            </label>
            <label class="block">
              <span class="mb-1 block text-xs font-medium text-[var(--color-muted-foreground)]">Parallel downloads</span>
              <input
                type="number"
                min="1"
                max="32"
                value={settings.concurrency}
                onInput={numInput("concurrency")}
                class="w-full rounded-lg border border-[var(--color-border)] bg-transparent px-3 py-2 text-sm outline-none focus:border-[var(--color-primary)] focus:ring-2 focus:ring-[var(--color-primary)]/20 transition-colors"
              />
              <p class="mt-1 text-[10px] text-[var(--color-muted-foreground)]">Higher = faster but more rate limits</p>
            </label>
          </div>
        </section>

        {/* Library folder */}
        <section class="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5">
          <h2 class="mb-3 text-sm font-semibold">Library Folder</h2>
          <label>
            <span class="sr-only">Library folder path</span>
            <input
              type="text"
              value={settings.libraryRoot}
              onInput={(e) => {
                setSettings("libraryRoot", e.currentTarget.value);
                saveSettings();
              }}
              class="w-full rounded-lg border border-[var(--color-border)] bg-transparent px-3 py-2 font-mono text-xs outline-none focus:border-[var(--color-primary)] focus:ring-2 focus:ring-[var(--color-primary)]/20 transition-colors"
            />
          </label>
        </section>

        {/* SearXNG */}
        <section class="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5">
          <h2 class="mb-1 text-sm font-semibold">Search Infrastructure</h2>
          <p class="mb-4 text-xs text-[var(--color-muted-foreground)]">
            SearXNG is a privacy-respecting metasearch engine. With Docker installed,
            one click spins up a local instance and enables it as a search source.
          </p>
          <div class="space-y-4">
            <button
              onClick={handleSetupSearx}
              disabled={settingUpSearx()}
              class="flex items-center gap-2 rounded-lg border border-[var(--color-border)] px-4 py-2 text-sm font-medium hover:bg-[var(--color-accent)] transition-colors disabled:opacity-50"
            >
              <Show when={settingUpSearx()} fallback={<Server size={14} />}>
                <Loader2 size={14} class="animate-spin" />
              </Show>
              {settingUpSearx() ? "Setting up… (may take a few minutes)" : "Setup SearXNG with Docker"}
            </button>

            <label class="block">
              <span class="mb-1 block text-xs font-medium text-[var(--color-muted-foreground)]">SearXNG instance URL</span>
              <input
                type="text"
                value={settings.searxngUrl}
                onInput={(e) => {
                  setSettings("searxngUrl", e.currentTarget.value);
                  saveSettings();
                }}
                placeholder="http://localhost:8080"
                class="w-full rounded-lg border border-[var(--color-border)] bg-transparent px-3 py-2 font-mono text-xs outline-none focus:border-[var(--color-primary)] focus:ring-2 focus:ring-[var(--color-primary)]/20 transition-colors"
              />
              <p class="mt-1 text-[10px] text-[var(--color-muted-foreground)]">
                Local or remote SearXNG instance
              </p>
            </label>

            <Show when={searxResult() !== null}>
              <div class="flex items-start gap-2 rounded-lg border p-3"
                style={{ "border-color": "color-mix(in oklch, var(--color-success) 30%, transparent)", "background-color": "var(--color-success-bg)" }}
              >
                <CheckCircle2 size={14} class="mt-0.5 shrink-0" style={{ color: "var(--color-success)" }} />
                <div>
                  <p class="text-xs font-medium" style={{ color: "var(--color-success-fg)" }}>SearXNG is running at {settings.searxngUrl}</p>
                  <Show when={searxResult()}>
                    <pre class="mt-1 max-h-24 overflow-auto whitespace-pre-wrap font-mono text-[10px] opacity-80" style={{ color: "var(--color-success-fg)" }}>
                      {searxResult()}
                    </pre>
                  </Show>
                </div>
              </div>
            </Show>

            <Show when={searxError()}>
              <div class="rounded-lg border border-[var(--color-destructive)]/30 bg-[var(--color-destructive)]/5 p-3 text-xs text-[var(--color-destructive)]">
                <p class="font-medium">Setup failed</p>
                <p class="mt-0.5 opacity-80">{searxError()}</p>
              </div>
            </Show>
          </div>
        </section>

        {/* Run log */}
        <section class="rounded-xl border border-[var(--color-border)] bg-[var(--color-card)] p-5">
          <h2 class="mb-1 text-sm font-semibold">Run Log</h2>
          <p class="mb-4 text-xs text-[var(--color-muted-foreground)]">
            Every query, source error, and download outcome is logged here.
            Share this file when reporting issues.
          </p>
          <Show
            when={logInfo()}
            fallback={<p class="text-xs text-[var(--color-muted-foreground)]">Unavailable</p>}
          >
            {(info) => (
              <div class="space-y-3">
                <code
                  title={info().path}
                  class="block truncate rounded-lg border border-[var(--color-border)] bg-[var(--color-muted)] px-3 py-2 font-mono text-[11px]"
                >
                  {info().path}
                </code>
                <p class="text-xs text-[var(--color-muted-foreground)]">
                  {info().exists ? formatBytes(info().size_bytes) : "Not yet written"}
                </p>
                <div class="flex gap-2">
                  <button
                    onClick={() => api.revealInFinder(info().path)}
                    disabled={!info().exists}
                    class="flex items-center gap-1.5 rounded-lg border border-[var(--color-border)] px-3 py-1.5 text-xs font-medium hover:bg-[var(--color-accent)] transition-colors disabled:opacity-40"
                  >
                    <FolderOpen size={12} />
                    Show in Finder
                  </button>
                  <button
                    onClick={async () => setLogInfo(await api.runLogInfo().catch(() => null))}
                    class="flex items-center gap-1.5 rounded-lg border border-[var(--color-border)] px-3 py-1.5 text-xs font-medium hover:bg-[var(--color-accent)] transition-colors"
                  >
                    <FileText size={12} />
                    Refresh
                  </button>
                </div>
              </div>
            )}
          </Show>
        </section>
      </div>
    </div>
  );
}
