// src/App.tsx
import { Switch, Match } from "solid-js";
import Sidebar from "@/components/Sidebar";
import FindTab from "@/components/FindTab";
import LibraryView from "@/components/LibraryView";
import SettingsView from "@/components/SettingsView";
import FirstRunModelDialog from "@/components/FirstRunModelDialog";
import { uiStore } from "@/stores/ui";

export default function App() {
  return (
    <div class="flex h-screen w-screen overflow-hidden bg-[var(--color-background)] text-[var(--color-foreground)]">
      {/* macOS traffic light drag region */}
      <div class="fixed inset-x-0 top-0 h-8 z-50 pointer-events-none" data-tauri-drag-region aria-hidden="true" />
      <Sidebar />
      <main id="main-content" tabindex="-1" class="flex-1 overflow-hidden outline-none">
        <Switch>
          <Match when={uiStore.view === "find"}><FindTab /></Match>
          <Match when={uiStore.view === "library"}><LibraryView /></Match>
          <Match when={uiStore.view === "settings"}><SettingsView /></Match>
        </Switch>
      </main>
      <FirstRunModelDialog />
    </div>
  );
}

// src/App.svelte
<script lang="ts">
  import Sidebar from "./components/Sidebar.svelte";
  import FindTab from "./components/FindTab.svelte";
  import LibraryView from "./components/LibraryView.svelte";
  import SettingsView from "./components/SettingsView.svelte";
  import { uiStore } from "./stores/ui.svelte";
</script>

<div class="flex h-screen w-screen overflow-hidden bg-[var(--color-background)] text-[var(--color-foreground)]">
  <Sidebar />
  <main class="flex flex-1 flex-col overflow-hidden">
    <div
      class="h-8 shrink-0 border-b border-[var(--color-border)]"
      data-tauri-drag-region
    ></div>
    <div class="flex-1 overflow-auto p-6">
      {#if uiStore.view === "find"}
        <FindTab />
      {:else if uiStore.view === "library"}
        <LibraryView />
      {:else if uiStore.view === "settings"}
        <SettingsView />
      {/if}
    </div>
  </main>
</div>
